# Generated by Django 4.2.19 on 2025-02-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0010_remove_hall_block_name_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_type', models.CharField(choices=[('PBE', 'PBE'), ('CBE', 'CBE')], max_length=50)),
                ('exam_period', models.CharField(max_length=50)),
                ('exam_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invigilation.hall')),
                ('invigilator1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_invigilator1', to='invigilation.lecturer')),
                ('invigilator2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_invigilator2', to='invigilation.lecturer')),
            ],
        ),
    ]
