# Generated by Django 4.2.19 on 2025-03-01 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0011_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text='Department (DEPT)', max_length=255)),
                ('academic_degree', models.CharField(help_text='Academic Degree', max_length=100)),
                ('name', models.CharField(help_text='Supervisor Name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamHallAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Example: 4', max_length=10)),
                ('course_code', models.CharField(help_text='Example: COMP 213', max_length=20)),
                ('course_name', models.CharField(help_text='Example: Programming - 29', max_length=255)),
                ('section', models.CharField(blank=True, help_text='Section (if applicable)', max_length=10, null=True)),
                ('total_students', models.PositiveIntegerField(help_text='Total number of students')),
                ('students_per_room', models.PositiveIntegerField(help_text='Number of students per room')),
                ('from_to', models.CharField(help_text='From-To range (e.g., 18-19)', max_length=50)),
                ('room_nos', models.CharField(help_text='Room numbers (comma separated, e.g., F12,F13)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_supervisor', models.ForeignKey(blank=True, help_text='Select the first supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_supervisor_halls', to='invigilation.examsupervisor')),
                ('second_supervisor', models.ForeignKey(blank=True, help_text='Select the second supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_supervisor_halls', to='invigilation.examsupervisor')),
            ],
        ),
    ]
