# Generated by Django 4.2.19 on 2025-03-15 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invigilation', '0013_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_notifs', related_query_name='invigilation_notifs', to=settings.AUTH_USER_MODEL),
        ),
    ]
