# Generated by Django 4.2.19 on 2025-03-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0014_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examhallassignment',
            options={'ordering': ['exam_date', 'exam_period', 'course_code']},
        ),
        migrations.AddField(
            model_name='examhallassignment',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Date of the exam', null=True),
        ),
        migrations.AddField(
            model_name='examhallassignment',
            name='exam_period',
            field=models.CharField(blank=True, choices=[('AM', 'Morning'), ('PM', 'Afternoon')], help_text='Exam period (Morning/Afternoon)', max_length=2, null=True),
        ),
        migrations.AddConstraint(
            model_name='examhallassignment',
            constraint=models.UniqueConstraint(fields=('first_supervisor', 'exam_date', 'exam_period'), name='unique_first_supervisor_schedule'),
        ),
        migrations.AddConstraint(
            model_name='examhallassignment',
            constraint=models.UniqueConstraint(fields=('second_supervisor', 'exam_date', 'exam_period'), name='unique_second_supervisor_schedule'),
        ),
    ]
