# Generated by Django 4.2.19 on 2025-03-29 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invigilation', '0015_alter_examhallassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(choices=[(False, 'غير محلول'), (True, 'محلول')], default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invigilation.examhallassignment')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.hall')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.lecturer')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.examsupervisor')),
            ],
        ),
    ]
