# Generated by Django 4.2.19 on 2025-03-30 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invigilation', '0016_conflict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflict',
            options={'ordering': ['-created_at'], 'verbose_name': 'تعارض', 'verbose_name_plural': 'تعارضات'},
        ),
        migrations.AddField(
            model_name='conflict',
            name='related_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conflict',
            name='related_object_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conflict',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='conflict_type',
            field=models.CharField(choices=[('LECTURER', 'تعارض محاضر'), ('HALL', 'تعارض قاعة'), ('TIMING', 'تعارض توقيت'), ('SUPERVISOR', 'تعارض مراقب')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Conflict1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(choices=[(False, 'غير محلول'), (True, 'محلول')], default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('exam_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invigilation.examhallassignment')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.hall')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.lecturer')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.examsupervisor')),
            ],
        ),
    ]
