# Generated by Django 4.2.19 on 2025-04-14 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0017_alter_conflict_options_conflict_related_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conflict',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conflict', 'verbose_name_plural': 'Conflicts'},
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='conflict',
            name='related_object_type',
        ),
        migrations.AddField(
            model_name='conflict',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.exam'),
        ),
        migrations.AddField(
            model_name='conflict',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conflict',
            name='exam_period',
            field=models.CharField(blank=True, choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('12-2', '12:00 - 14:00'), ('2-4', '14:00 - 16:00'), ('4-6', '16:00 - 18:00')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='conflict_type',
            field=models.CharField(choices=[('LECTURER', 'Lecturer Conflict'), ('HALL', 'Hall Conflict'), ('TIMING', 'Timing Conflict'), ('SUPERVISOR', 'Supervisor Conflict')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='exam_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invigilation.examhallassignment'),
        ),
        migrations.AlterField(
            model_name='conflict',
            name='resolved',
            field=models.BooleanField(choices=[(False, 'Unresolved'), (True, 'Resolved')], default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_period',
            field=models.CharField(choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('12-2', '12:00 - 14:00'), ('2-4', '14:00 - 16:00'), ('4-6', '16:00 - 18:00')], help_text='Select exam time period', max_length=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('PBE', 'Paper Based Exam'), ('CBE', 'Computer Based Exam')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examhallassignment',
            name='exam_date',
            field=models.DateField(help_text='Date of the exam'),
        ),
        migrations.AlterField(
            model_name='examhallassignment',
            name='exam_period',
            field=models.CharField(choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('12-2', '12:00 - 14:00'), ('2-4', '14:00 - 16:00'), ('4-6', '16:00 - 18:00')], help_text='Exam time period', max_length=5),
        ),
    ]
